### ISSUE TITLE
Run-time dependency fmt found: NO (tried pkgconfig and cmake)

### ISSUE THREAD

**Issue by strk** [guysherman/jack-passthrough#3]
$ meson setup build
...
Run-time dependency fmt found: NO (tried pkgconfig and cmake)
...
$ which fmt
/usr/bin/fmt

**Comment by strk** [comment]
Installing libfmt-dev package (as mentioned in the README) fixed the build. I guess it would have been more clear if the error mentioned _libfmt_ instead of just _fmt_

**Comment by strk** [comment]
Closing as it doesn't look like we control the error message but it's something nested into meson itself

**Comment by eli-schwartz** [comment]
Well, "fmt" is the name of the pkg-config dependency (the GNU coreutils shell program would be reported, if meson could not find it via `find_program('fmt')`, as "Program 'fmt' not found or not executable").

By the way, you *can* control the error message: since meson 0.50.0, you can specify `not_found_message: 'my text string'` as a kwarg to the dependency() function, and meson will print it whenever the dependency is not found.

Also, you can avoid error messages entirely, if you wish, by running `mkdir subprojects; meson wrap install fmt` and optionally committing `subprojects/fmt.wrap` to git. If you do this, you might want to also specify `dependency('fmt', default_options: ['default_library=static'])` to ensure that fmt will always be built as a static internal library if it is being built as a private copy, unless the user manually configures meson with `-Dfmt:default_library=...`.
